name: CI

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v2
        with:
          deno-version: "2.x"

      - name: Lint
        run: deno lint .

      - name: Test
        run: deno test --allow-all

      - name: Compile
        run: deno task compile:cli
